[browser]
gatherUsageStats = false

[logger]
# Level of logging: 'error', 'warning', 'info', or 'debug'.
# Default: 'info'
level = "info"

[theme]
primaryColor = "#4e8855"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#ebf1e2"
textColor = "#4e524c"
font = "sans serif"
